spring.application.name=HotelBooking
spring.data.mongodb.uri=mongodb+srv://soorya7n:8IjRWeSFpmjL2pvy@clusterms01.r5ylksn.mongodb.net/Maharajas
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.mapping.auto-index-creation=true
spring.data.mongodb.type-key=none
spring.jackson.time-zone=Asia/Kolkata
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.mvc.view.include-bean-name=false
spring.mvc.static-path-pattern=/static/**
spring.resources.static-locations=classpath:/static/